// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	addressFieldNames          = builder.RawFieldNames(&Address{})
	addressRows                = strings.Join(addressFieldNames, ",")
	addressRowsExpectAutoSet   = strings.Join(stringx.Remove(addressFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	addressRowsWithPlaceHolder = strings.Join(stringx.Remove(addressFieldNames, "`id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheZeroUserAddressIdPrefix = "cache:zeroUser:address:id:"
)

type (
	addressModel interface {
		Insert(ctx context.Context, data *Address) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Address, error)
		Update(ctx context.Context, newData *Address) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAddressModel struct {
		sqlc.CachedConn
		table string
	}

	Address struct {
		Id         int64        `db:"id"` //
		Uid        string       `db:"uid"`
		Name       string       `db:"name"`        // 收件人姓名
		Mobile     string       `db:"mobile"`      // 收件人电话
		Province   string       `db:"province"`    // 省份
		City       string       `db:"city"`        // 市(直辖市区)
		Dist       string       `db:"dist"`        // 区
		Address    string       `db:"address"`     // 详细地址
		IsDefault  int64        `db:"is_default"`  // 是否默认地址 0 否 1是
		IsDelete   int64        `db:"is_delete"`   // 是否删除 0 否 1 是
		CreateTime time.Time    `db:"create_time"` // 创建时间
		UpdateTime time.Time    `db:"update_time"` // 更新时间
		DeleteTime sql.NullTime `db:"delete_time"` // 删除时间
	}
)

func newAddressModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultAddressModel {
	return &defaultAddressModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`address`",
	}
}

func (m *defaultAddressModel) Delete(ctx context.Context, id int64) error {
	zeroUserAddressIdKey := fmt.Sprintf("%s%v", cacheZeroUserAddressIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, zeroUserAddressIdKey)
	return err
}

func (m *defaultAddressModel) FindOne(ctx context.Context, id int64) (*Address, error) {
	zeroUserAddressIdKey := fmt.Sprintf("%s%v", cacheZeroUserAddressIdPrefix, id)
	var resp Address
	err := m.QueryRowCtx(ctx, &resp, zeroUserAddressIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", addressRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAddressModel) Insert(ctx context.Context, data *Address) (sql.Result, error) {
	zeroUserAddressIdKey := fmt.Sprintf("%s%v", cacheZeroUserAddressIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, addressRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Uid, data.Name, data.Mobile, data.Province, data.City, data.Dist, data.Address, data.IsDefault, data.IsDelete, data.DeleteTime)
	}, zeroUserAddressIdKey)
	return ret, err
}

func (m *defaultAddressModel) Update(ctx context.Context, data *Address) error {
	zeroUserAddressIdKey := fmt.Sprintf("%s%v", cacheZeroUserAddressIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, addressRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Uid, data.Name, data.Mobile, data.Province, data.City, data.Dist, data.Address, data.IsDefault, data.IsDelete, data.DeleteTime, data.Id)
	}, zeroUserAddressIdKey)
	return err
}

func (m *defaultAddressModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheZeroUserAddressIdPrefix, primary)
}

func (m *defaultAddressModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", addressRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAddressModel) tableName() string {
	return m.table
}
